### ISSUE TITLE
Abort request from vue-axios

### ISSUE THREAD

**Issue by aswinkp** [imcvampire/vue-axios#10]
I saw the cancellation feature for the Axios. But I am not able to cancel in vue-axios.
Is there any way that I could cancel all the API requests in the current component from beforeDestroy().

Hint: I am using Vue.axios.get() inside vue method that is triggered from created().

**Comment by sc0Vu** [comment]
Maybe you should see this: [link](https://github.com/mzabriskie/axios#cancellation)

Use CancelToken to stop request.
