### ISSUE TITLE
"npm run build" reports this error

### ISSUE THREAD

**Issue by Sphinxone** [imcvampire/vue-axios#102]
When i build my vue project,i got this error.

WARNING in ./src/main.js
23:8-16 "export 'default' (imported as 'VueAxios') was not found in 'vue-axios'
 @ ./src/main.js

ERROR in static/js/vendor.334ceea9e3e48015f1fc.js from UglifyJs
Unexpected token name «NODE_ENV», expected punc «,» [./node_modules/vue-axios/dist/vue-axios.es5.js:1,3159][static/js/vendor.334ceea9e3e48015f1fc.js:
35428,173]

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-webgis@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-webgis@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

i have searched many method,but i can not solve this problem.

**Comment by Alanscut** [comment]
hi @Sphinxone, could you provide your vue and vue-axios version, or link a simple demo? I tested with vue 2/3 + vue-aixos@3.2.5, and can't reproduce above error.

**Comment by Sphinxone** [comment]
> hi @Sphinxone, could you provide your vue and vue-axios version, or link a simple demo? I tested with vue 2/3 + vue-aixos@3.2.5, and can't reproduce above error.

thanks for your reply!

my two project all report this problem.

my vue and vue-axios is following:
"vue-axios": "^3.2.4"
"vue": "^2.5.2"
"axios": "^0.21.1"

i try to use vue-axios@3.2.5 and report same problem

**Comment by Alanscut** [comment]
@Sphinxone Please try removing `^` from `"vue-axios": "^3.2.4"`, because `^` symbol  indicates that the latest version of the current minor version is downloaded, so at last you are still using `vue-axios@3.2.5`.

the build format changed to `umd` in `v3.2.5`, which may cause above error. could you provide your build.js script?

**Comment by Alanscut** [comment]
vue-axios@3.2.5 also support  Vue 2, please see my demo: https://github.com/Alanscut/vue-axios-test

serve the `server/app.js` first, then run the vue project with `npm run serve`, you will find the vue 2 works well with vue-axios@3.2.5.
