### ISSUE TITLE
weight full vue report ?

### ISSUE THREAD

**Issue by hotrungnhan** [imcvampire/vue-axios#104]
![image](https://user-images.githubusercontent.com/40029631/130968271-cc752b84-24a7-4e0b-aa3d-80221cbf3f57.png)
the generate report of vue tell me that vue axios it so weightful for this kind of wrapper, I guess that you can build esm bundle to retrive much smaller size.

**Comment by imcvampire** [comment]
@hotrungnhan Agree! Could you have any time to help me with it?

**Comment by hotrungnhan** [comment]
Ok , I'll take this

**Comment by hotrungnhan** [comment]
![image](https://user-images.githubusercontent.com/40029631/132182892-2a983068-9377-4aeb-b651-9aa3893ee88d.png)
Now it just cost 1 kb  #[105](https://github.com/imcvampire/vue-axios/pull/105)

**Comment by hotrungnhan** [comment]
By some unknown reason the esm bundle was't built when push to npm , could u check it ?

**Comment by imcvampire** [comment]
Seems like there is an error with your build script 
<img width="1494" alt="Screenshot 2021-09-08 at 2 11 50 am" src="https://user-images.githubusercontent.com/9426721/132421789-2b4ebb3d-5912-4e9e-9570-1f6070f634d0.png">

**Comment by hotrungnhan** [comment]
it cause by uglify package. i dont know why last time it still properly , now it been change to gulp-uglify-es which is 100% es6 support

**Comment by imcvampire** [comment]
Fixed by #106 #105
