### ISSUE TITLE
在使用post发送请求时有10%的几率会发送两次请求

### ISSUE THREAD

**Issue by shooke** [imcvampire/vue-axios#11]
我在开发的过程中遇到了一个问题，当我执行这段代码的时候，他会有5%-10%的几率，额外发送一个options类型的请求。
```
this.$http.post(this.apiUrl + 'wechat/bind', {
                    appid: this.ruleForm.appid,
                    appsecrect: this.ruleForm.appsecrect
                }).then(response => {

                    console.log(response);

            }, response => {
                    console.log(response);
                });
```
发生额外请求时，用chrome查看是这样的

## General
Request URL:http://localhost/chapiaoling/api/index.php/wechat/bind
**Request Method:OPTIONS**
Status Code:200 OK
Remote Address:[::1]:80
Referrer Policy:no-referrer-when-downgrade
## Response Headers
HTTP/1.1 200 OK
Date: Sat, 20 May 2017 17:40:18 GMT
Server: Apache/2.4.23 (Win64) PHP/5.6.25
X-Powered-By: PHP/5.6.25
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: content-type
**Access-Control-Request-Method: GET,POST**
Content-Length: 101
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
## Request Headers
OPTIONS /chapiaoling/api/index.php/wechat/bind HTTP/1.1
Host: localhost
Connection: keep-alive
**Access-Control-Request-Method: POST**
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: zh-CN,zh;q=0.8

请求时是Access-Control-Request-Method: POST 但chrome的General中显示的请求确是Request Method:OPTIONS，我在服务气端用`$_SERVER['REQUEST_METHOD']`查看请求方式也是OPTIONS。希望尽快修复此bug。

**Comment by sc0Vu** [comment]
嗨
這個套件只是包覆原先這個[套件](https://github.com/mzabriskie/axios)
可以去那邊追蹤程式碼
不過你遇到的問題
先前使用vue-resource也有遇過
這看起來不是套件的問題
你可以參考這邊[文章](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests)
只要符合裡面的非簡易請求
都會先發option的請求確認跨站問題

**Comment by pexea12** [comment]
你应该用英语说 我们不知道你在说什么

You should speak in English. We don't know what you are talking about.

**Comment by seekcx** [comment]
这个是因为服务器使用的CORS来进行跨域，OPTIONS是非简单请求前的预检请求，如果服务器端响应了max-age，则在此期间不会再次发送预检请求。

http://www.ruanyifeng.com/blog/2016/04/cors.html

**Comment by AkatQuas** [comment]
@pexea12 
they are talking about why there being two requests sent when using `POST` request, and the reason is [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) control.
Kinda late since 4 months past, haha

**Comment by jstzzz** [comment]
同求如何解决

**Comment by dunhuang** [comment]
跨域时，request的header的content-type设为'text/plain' , 发送的data必须为string类型（json数据用JSON.stringify()处理一下），即可解决这个问题。

when it is a CORS request, you should set content-type as 'text/plain' in the request' header, and request data body must be String type. There will be no OPTIONS request

demo:
```
axios.post(this.apiUrl + 'wechat/bind',
  {
      headers: {'Content-type': 'text/plain'},
      data: JSON.stringify({
          appid: this.ruleForm.appid,
          appsecrect: this.ruleForm.appsecrect
       })
   }
)
```
