### ISSUE TITLE
It's possible to use 2 instances?

### ISSUE THREAD

**Issue by amandiobm** [imcvampire/vue-axios#111]
Hey all, 

Was reading through old issues and I found these:
 - #28
 - #8 

Both are closed but none of those methods works as suggested.

There is a way to have 2 instances of this?

Thanks.

**Comment by imcvampire** [comment]
Have you tried this code? 
```js
let firstInstance = axios.create()
let secondInstance = axios.create()

Vue.use(VueAxios, {
  first: firstInstance,
  second: secondInstance
})

// available Vue.$http.first and Vue.$http.second
```
