### ISSUE TITLE
Error due to working with multiple components

### ISSUE THREAD

**Issue by ATLANT-Z** [imcvampire/vue-axios#122]
If you use several components, and pass for each VueAxios to the use method, it will only work in the first component, in the rest axios will be undefined

```
import axios from "axios";
import VueAxios from "vue-axios";

import productSlider from "@component/Slider";
import globalFunc from "@/tools/globalFunc";

const sliders = document.querySelectorAll(".app-product-slider");
for (const slider of sliders) { 
	createApp(productSlider).use(VueAxios, axios).use(store).use(globalFunc).mount(slider);
	// Only in first slider will works
}
```

**Comment by imcvampire** [comment]
Not sure why do you need to `createApp` multiple times. Could you provide a minimal reproduction?

**Comment by ATLANT-Z** [comment]
I use multiple VUE components in different places for different ids or classes.
This is necessary so that part of the content is loaded statically for SEO, and part is a VUE component that replaces the static after the script is executed, or supplements it.

That's my `main.js `

```

import { createApp } from "vue";

import i18n from "./i18n";
import store from "./store";
import router from "./router";
import axios from "axios";
import VueAxios from "vue-axios";
import GlobalFunctions from "@/tools/globalFunc";

import PrivateOffice from "./PrivateOffice.vue";
import Header from "@component/Header/Header";

// eslint-disable-next-line no-unused-vars
//.use(i18in)
createApp(PrivateOffice).use(router).use(store).use(VueAxios, axios).use(GlobalFunctions).mount("#appOffice"); //works
createApp(Header).use(router).use(store).use(VueAxios, axios).use(GlobalFunctions).mount("#appHeader"); // this.axios === undefined

window.axios = axios; //BugFix
```


It doesn't matter what the component is, even if it's just 2 empty components, then in the first `this.axios` will work, and in the second `this.axios` will be `undefined`

**Comment by imcvampire** [comment]
Maybe because of this check https://github.com/imcvampire/vue-axios/blob/master/src/index.js#L7 🤔

**Comment by ATLANT-Z** [comment]
Most likely!
The check is good, but only if the `installed `field refers not to the plugin, but to the object for which the plugin is being installed.

Smth like this
```
if(app['vueAxiosInstalled']) {
     return
}
```
