### ISSUE TITLE
Confusing table in README.md

### ISSUE THREAD

**Issue by Blitheness** [imcvampire/vue-axios#143]
Can this be made more explicit please? It seems unclear which versions are for which product.

![image](https://user-images.githubusercontent.com/19779808/195338991-e5754d9b-b3f9-401b-877d-f47676567ac3.png)

**Comment by imcvampire** [comment]
Do you have any suggestions?

**Comment by imcvampire** [comment]
https://github.com/imcvampire/vue-axios/pull/144

**Comment by Blitheness** [comment]
You could maybe drop v1 from that table, but there is still widespread usage of Vue 2. 

Perhaps something like this?

| VueAxios v.: | 1.x | 2.x | 3.x |
|--------------|-----|-----|-----|
| Vue 1.x      | ✅   | ✅   | ✅   |
| Vue 2.x      | ✅   | ✅   | ✅   |
| Vue 3.x      | ❌   | ❌   | ✅   |


| VueAxios v.: | 2.x | 3.x |
|--------------|-----|-----|
| Vue 2.x      | ✅   | ✅   |
| Vue 3.x      | ❌   | ✅   |

**Comment by imcvampire** [comment]
Doesn't vue-axios v3 support vue v2 and v3? I don't think there is anyone who still need to use vue-axios v2 if they start from scratch now
