### ISSUE TITLE
Axios to 1.0.0 update problem

### ISSUE THREAD

**Issue by Savuelo** [imcvampire/vue-axios#148]
The recent package update to 3.5.0 caused a problem in my copier (https://copier.readthedocs.io/en/stable/) managed projects. 
I cannot update the project because of the dependency error. Copier tries to install the historic dependencies to track the changes but it fails due to version missmatch. I have declared that I require vue axios in version `vue-axios@"^3.4.1"`, and also an axios `axios@0.27.2`. This configuration was fine until `vue-axios` package wasn't updated to `3.5.0` with dependency for `axios >=1.0.0`. Now I can't perform update process.
I cannot update historic copier-template release to fix the dependencies. 

I would ask you to release a new version of this package with the previous version of axios, and add 1.0.0 support as a new major.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: axios@0.27.2
npm ERR! node_modules/axios
npm ERR!   axios@"^0.27.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer axios@">=1.0.0" from vue-axios@3.5.1
npm ERR! node_modules/vue-axios
npm ERR!   vue-axios@"^3.4.1" from the root project
```

**Comment by struginskij** [comment]
Same here, plz send help

**Comment by Savuelo** [comment]
FYI, it's not problem with npm/node, deleting `node_modules` and/or `package-lock.json` does not solve the issue.

**Comment by akucinskii** [comment]
我也有这个问题

**Comment by imcvampire** [comment]
What is your `package.json`? Seems like you add an entry for `axios` there, which requires `^0.27.2`. `vue-axios` wants `axios@^1.0.0`. As there is no version to be compatible with both `^0.27.2` and `^1.0.0`, `npm` throws that error. My suggestion is you run `npm install axios@^1.0.0` (or change `package.json`) manually.

**Comment by struginskij** [comment]
It would be too easy. I've got the same situation as Savusiemano, I am not able to modify `package.json` at all.

**Comment by imcvampire** [comment]
I think I can change `vue-axios` to any `axios` version

**Comment by Savuelo** [comment]
I would be grateful, I hope this helps

**Comment by imcvampire** [comment]
https://github.com/imcvampire/vue-axios/releases/tag/3.5.2 should resolve this problem!
