### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by decadehew** [imcvampire/vue-axios#16]
當我根據vue-axios指導方式去引用axios時
```
Vue.axios.get(api).then((response) => {
  console.log(response.data)
})

this.axios.get(api).then((response) => {
  console.log(response.data)
})

this.$http.get(api).then((response) => {
  console.log(response.data)
})
```
第一個Vue.axios就失敗顯示error 
**Vue is not defined**

其他兩個沒問題！

有人和我一樣嗎？謝謝

**Comment by imcvampire** [comment]
Do you `import` or `require` Vue?

```
import Vue from 'vue'
```
or
``` 
const Vue = require('vue')
```

**Comment by lee-joe** [comment]
你试着用
`
axios.get(api).then((response) => {
  console.log(response.data)
})
`

看看行不行

**Comment by TDodgeCo** [comment]
@lee-joe I believe that since `vue-axios` is now part of the vue instance, you need to call it like so:

`this.axios.get(api).then(response => { console.log(response.data) })`
