### ISSUE TITLE
the different between Vue.prototype and vue-axios?

### ISSUE THREAD

**Issue by fengxuway** [imcvampire/vue-axios#18]
```
import axios from 'axios'
Vue.prototype.axios = axios
```
or
```
import axios from 'axios'
Vue.use(VueAxios, axios)
```

**Comment by mastermunj** [comment]
From what I understand, the first block of code merely assigns axios instance to prototype.axios property whereas second block runs the VueAxios plugin with two parameters Vue & axios, inside there it sets axios to Vue global as well as at prototype level & $http to prototype level.

@imcvampire may add more if I've misunderstood any part here.

**Comment by imcvampire** [comment]
It's mostly the same!

But in VueAxios, I use `Object.defineProperties` so it will make property `axios` and `$http` immutable!
