### ISSUE TITLE
index.d.ts cause error

### ISSUE THREAD

**Issue by lusess123** [imcvampire/vue-axios#24]
node_modules/_vue-axios@2.1.1@vue-axios/index.d.ts(6,13): error TS2451: Cannot redeclare block-scoped variable 'Vue'.

**Comment by imcvampire** [comment]
@asulta @s-KaiNet Can you help me resolve this problem?

**Comment by s-KaiNet** [comment]
A quick fix will be adding ` "skipLibCheck": true,` into the `tsconfig.json`    
For the long term we need to fix definition because it seems it's not compatible with the latest TS version.

**Comment by evenfrost** [comment]
https://github.com/imcvampire/vue-axios/pull/30 should fix it (works locally).
