### ISSUE TITLE
Can't import VueAxios in typescript

### ISSUE THREAD

**Issue by olegshtch** [imcvampire/vue-axios#25]
I'm trying to use vue-axios in typescript project but get errors even on import:

```typescript
import VueAxios from 'vue-axios'; // has no default export.
import * as VueAxios from 'vue-axios'; // resolves to a non-module entity and cannot be imported using this construct.
import VueAxios = require('vue-axios'); // Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
import { VueAxios } from 'vue-axios'; // has no exported member 'VueAxios'.
```

Should consider VueAxios to be default export? Or there some other methods to import the plugin?

Versions:
vue-axios: 2.1.1
typescript: 2.8.1

tsconfig.json:
```json
{
  "compilerOptions": {
    "outDir": "./src/main/webapp/",
    "sourceMap": true,
    "noImplicitAny": false,
    "module": "es2015",
    "target": "es5",
    "strict": true,
    "jsx": "react",
    "allowJs": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true
  }
}
```

**Comment by AlexSayHello** [comment]
I've the same problem, using typescript 2.8.1 with webpack and `ts-loader`

tsconfig.json:

```json
{
  "compilerOptions": {
    "outDir": "./built/",
    "sourceMap": true,
    "strict": true,
    "noImplicitReturns": true,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "experimentalDecorators": true
  },
  "include": [
    "./src/**/*"
  ]
}
```


 maybe you should change the export line for the type definition.


```typescript
//index.d.ts
declare class VueAxios {
  static install: PluginFunction<AxiosInstance>;
}

export default VueAxios
```

**Comment by olegshtch** [comment]
Same for `typescript: 2.8.3` and `target: es6`.

**Comment by olegshtch** [comment]
> maybe you should change the export line for the type definition.

Yep, it allows to import VueAxios.

```typescript
import VueAxios from 'vue-axios';
```

But looks like property `axios` wasn't added to `Vue` type from `'vue'`, but I'm not sure how to import `Vue` type from `'vue-axios'`.

**Comment by anorborg** [comment]
Has anyone manged to get this working? Or is there an issue with the types?

**Comment by imcvampire** [comment]
Hi all, have you try the solution in this issue https://github.com/imcvampire/vue-axios/issues/24

**Comment by anorborg** [comment]
issue #24 fixes the import, but then loses the typing information for `Vue.axios`

**Comment by evenfrost** [comment]
Is it still not working for you? I have no issues with
```ts
import VueAxios from 'vue-axios';
```
I've got other error with TS definition (#24), [this PR](https://github.com/imcvampire/vue-axios/pull/30) fixes it.

**Comment by bang88** [comment]
```ts
import { AxiosInstance } from "axios";
import { PluginFunction } from "vue";

declare module "vue/types/vue" {

  interface Vue {
    axios: AxiosInstance;
    $http: AxiosInstance;
  }

  // namespace Vue {
  //   const axios: AxiosInstance;
  // }

}

declare class VueAxios {
  static install: PluginFunction<AxiosInstance>;
}

export = VueAxios
```
It worked but I have to comment these lines.

**Comment by imcvampire** [comment]
Please check https://github.com/imcvampire/vue-axios/releases/tag/2.1.2. 

I publish a new version that fixes this issue

**Comment by ramarivera** [comment]
With version 2.1.2, I'm still getting errors on import :(

I've done the same as olegschtch

> import VueAxios from 'vue-axios'; // has no default export.
> import * as VueAxios from 'vue-axios'; // resolves to a non-module entity and cannot be imported using this construct.
> import { VueAxios } from 'vue-axios'; // has no exported member 'VueAxios'.

I've only just scaffolded the project using @vue/cli.

vue-axios version: 2.1.2
typescript version: 2.9.1 and 2.8.4 (tried both)
vue cli version: 3.0.0-rc.8

What's the right way to import VueAxios then?

Thanks!!

**Comment by imcvampire** [comment]
@evenfrost can you help me check the error above

**Comment by ramarivera** [comment]
In case it helps, changing the index.d.ts file to this:

```
import Vue, {PluginFunction, PluginObject} from "vue";
import {AxiosInstance} from "axios";

declare module "vue/types/vue" {

  interface Vue {
    axios: AxiosInstance;
    $http: AxiosInstance;
  }

}

declare class VueAxios {
  static install: PluginFunction<AxiosInstance>;
}

// export = VueAxios;

export default VueAxios;

```

allows me to use `import VueAxios from 'vue-axios';`

**Comment by Eltargrim** [comment]
I'm using the latest version, 2.1.2 at the time of writing. Which has the updated typings file referenced in this thread. I am not having any issues with the import specifically when using:

`import VueAxios from 'vue-axios';`

But I do not have typings on the Vue instance. Typescript is complaining that the property 'axios' ( or $http ) does not exist on the VueConstructor<Vue> type, and will not compile.

I have tried various versions of typescript, including the latest of 3.0.1.

Anyone have any suggestions?

**Comment by imcvampire** [comment]
Hi all, I have just changed `index.d.js` as @ramarivera suggested. Can anyone check it?

**Comment by mbale** [comment]
@imcvampire Still misses the part that allows calling axios on global Vue.

```
declare` module "vue/types/vue" {

  interface Vue {
    axios: AxiosInstance;
    $http: AxiosInstance;
  }

 // this
  interface VueConstructor {
    axios: AxiosInstance;
  }
}
```
