### ISSUE TITLE
It's possible to use 2 instances?

### ISSUE THREAD

**Issue by fabioebner** [imcvampire/vue-axios#28]
It's possible to use 2 instances from vue-axios, each one with a diff this.axios.defaults.baseURL ?

how ?

tks

**Comment by Vilvarin** [comment]
This code should work:

let firstInstance = axios.create()
let secondInstance = axios.create()

Vue.use(VueAxios, {
  first: firstInstance,
  second: secondInstance
})

// available Vue.$http.first and Vue.$http.second
