### ISSUE TITLE
What's the point of a wrapper?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [imcvampire/vue-axios#31]
Hi!

I was just wondering what's the point of using a vue wrapper for axios? What is the gain over a simple

```javascript
import axios from 'axios'

axios.get()
```
Does having it set in the Vue component allow me to do something useful (for example, easily set some globals : https://github.com/axios/axios#global-axios-defaults)?

Thanks :)

**Comment by imcvampire** [comment]
Hi,

I created this library because, in the past, I need a simple solution to migrate from `vue-resource` to `axios`. 

It has a small benefit that it binds `axios` to vue instance so you don't have to import everytime you use `axios`

**Comment by EmmanuelBeziat** [comment]
Okay, thanks for the tip! :)

**Comment by mrcodekiddie** [comment]
😌
