### ISSUE TITLE
Cannot redefine property: $http

### ISSUE THREAD

**Issue by misland** [imcvampire/vue-axios#34]
I got this error when I use this plugin,can anyone explain why?many thanks!!
version:
Vue:2.5.16
Vue-axios:2.1.4

vue-axios.min.js?de48:formatted:18 Uncaught TypeError: Cannot redefine property: $http
    at Function.defineProperties (<anonymous>)
    at o (vue-axios.min.js?de48:formatted:18)
    at Function.Vue.use (vue.esm.js?22f2:4753)
    at eval (main.js?3479:14)
    at Object../src/main.js (app.js:4860)
    at __webpack_require__ (app.js:708)
    at fn (app.js:113)
    at Object.0 (app.js:4892)
    at __webpack_require__ (app.js:708)
    at app.js:806

**Comment by imcvampire** [comment]
Do you use any others plugins

**Comment by misland** [comment]
> Do you use any others plugins

I use Element-UI

**Comment by imcvampire** [comment]
And do you define `Vue/$http` by yourself? Or any plugin does it?

**Comment by misland** [comment]
I didn't define $http myself,I didn't use other plugin besides ElementUI and axios,so I feel weird for this problem,following is my code:
`import ElementUI from 'element-ui'
Vue.use(ElementUI, {size: 'small'})

import Vueaxios from 'vue-axios'
import axios from 'axios'
Vue.use(Vueaxios,axios)`

**Comment by imcvampire** [comment]
Can you provide a minimal reproduction?

**Comment by Derasm** [comment]
Have you done this to redefine $http: 
Vue.prototype.$http = axios
? It comes recommended from here; 
https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4

**Comment by imcvampire** [comment]
@Derasm It's already defined https://github.com/imcvampire/vue-axios/blob/master/src/index.js#L31

**Comment by misland** [comment]
sorry,I didn't keep following this question now,you all can discuss continually :)

**Comment by vvrecord** [comment]
Vueresource package is not introduced in main.js, or it is not installed by NPM
maybe check if the vueresource package is installed, and then add the introduction in main.js.
