### ISSUE TITLE
Axios types appear to be wrong: AxiosInstance vs AxiosStatic

### ISSUE THREAD

**Issue by ktiedt** [imcvampire/vue-axios#35]
https://github.com/imcvampire/vue-axios/blob/30998f315db5dcfc5ce6867588554ae7ef51dc7a/index.d.ts#L2-L18

In the above code, based on local projects, `AxiosStatic` is the appropriate type here as it provides the static methods, `.all` `.spread` etc...

Updating my local node_modules package appears to fix the problem, but maybe someone is aware of a counter reason why `AxiosInstance` is correct?

**Comment by imcvampire** [comment]
@ktiedt Could you provide a Pull Request for this

**Comment by ThaDaVos** [comment]
I think AxiosInstance may be correct as you can configure all sorts of things on it, like interceptors etc - does the change to `AxiosStatic` mean you cannot anymore?

**Comment by chinesedfan** [comment]
Fixed by #43. And don't worry, because AxiosStatic extends from AxiosInstance. Now it can be closed.
