### ISSUE TITLE
Ignore baseURL on request

### ISSUE THREAD

**Issue by enbermudas** [imcvampire/vue-axios#37]
Hi! Is there a way to ignore the baseURL in a request? Right now i have a single get request that does not uses the baseURL that I have set and it looks like an awful solution to my problem:

``this.$http.get(`${this.$http.defaults.baseURL.replace('/api', '')}${this.providerCsvUrl}`)``

Thanks in advance!

**Comment by imcvampire** [comment]
`vue-axios` only wraps `axios` and do not add any new feature, please read the documentation of `axios` for your problem.

BTW, I found a solution that may help you https://stackoverflow.com/questions/54418135/use-different-base-urls-with-central-axios-create

**Comment by enbermudas** [comment]
@imcvampire I've found a better solution for my problem:

``this.$http.get(this.providerCsvUrl).setBaseURI('/')``

This method overrides the BaseURI and lets me do what i want without the use of that ugly template literal. Thanks anyway!
