### ISSUE TITLE
Why isn't there a Vue.$http

### ISSUE THREAD

**Issue by josefsabl** [imcvampire/vue-axios#49]
It would make much more sense. You also don't do: `Vue.$vuex` but `Vue.$store`. Is there any reason for this? I just tried changing

`Vue.axios = axios;`

to

`Vue.$http = axios;`

in your code and it seems to work.

**Comment by imcvampire** [comment]
There is already `Vue.$http` on `vue-axios`

**Comment by imcvampire** [comment]
I added it!

**Comment by josefsabl** [comment]
Will this ever get to be released? :-)
