### ISSUE TITLE
Accessing second lvl data?

### ISSUE THREAD

**Issue by jesperlandberg** [imcvampire/vue-axios#5]
Hi,

Unsure if this is related to vue-axios or not but here we go:
I am not able to access second lvl data for some reason "Cannot read property ... of undefined"

My code looks like the following:

```
	data() {
		return {
			project: {}
		}
	},
	beforeRouteEnter (to, from, next) {
 		const api = '/static/data/projects/' + to.params.slug + '.json'

		Vue.axios.get(api).then((response) => {
			next(vm => {
	          vm.project = response.data
	        })
		})
  	},
```
And the json i'm accessing like this:

```
{
	"title": "Vogue",
	"hero": "static/img/vogue/vogue-hero.jpg",
	"next": {
		"slug": "pointsbet",
		"thumb": "static/img/pointsbet/pointsbet-hero.jpg",
		"title": "Pointsbet"
	}
}
```

Any idea? project.title works fine, but not project.next.slug for example.

**Comment by imcvampire** [comment]
Can you post full of error?

**Comment by jesperlandberg** [comment]
@imcvampire sure.

it looks like this: https://puu.sh/ul2Xv/338adcd1cd.png

**Comment by imcvampire** [comment]
I think you are facing a problem when accessing some property in `<template>`. Error throws in `render` method.

**Comment by imcvampire** [comment]
Close because of no more infomation
