### ISSUE TITLE
There are several problems with vue-axios

### ISSUE THREAD

**Issue by xiaofan9** [imcvampire/vue-axios#58]
In the [npm.js](https://www.npmjs.com/package/vue-axios) website, the md document is wrong；

The code provided by [unpkg](https://unpkg.com/vue-axios) is outdated，That is, the code in the dist folder is out of date.This will also cause the vue-axios code introduced using import to be outdated 

In vue2 use, An error occurred :
![image](https://user-images.githubusercontent.com/16103130/95650477-872d2180-0b16-11eb-9e71-1ad4def5bd23.png)

**Comment by imcvampire** [comment]
Do you use `vue-axios` 3? Currently, it doesn't support vuejs 2.

**Comment by imcvampire** [comment]
Ah, the current version in both unpkg and npm doesn't the latest commit. The newest MR causes some problems so I haven't publish a new version. 

The README on npm is correct for it's version

**Comment by imcvampire** [comment]
I'm finding a way to use `rollup` to bundle `semver` with the build file. The latest MR introduces it as the first dependence.

**Comment by xiaofan9** [comment]
> 你用`vue-axios`3吗？目前，它不支持vuejs 2。

in 

> Do you use `vue-axios` 3? Currently, it doesn't support vuejs 2.

Use vue2. I see that the md document introduction already supports vue2

**Comment by imcvampire** [comment]
But that version hadn't been build successfully. The md document in npm is correct!

**Comment by xiaofan9** [comment]
to understanding, thinks!
