### ISSUE TITLE
Cannot instantiate VueAxios

### ISSUE THREAD

**Issue by avi12** [imcvampire/vue-axios#59]
In `main.js`, I have:
```js
import Vue from "vue";
import VueAxios from "vue-axios";
import axios from "axios";

Vue.use(VueAxios, axios);
// ...
```
But, I get an error:
```
vue-axios.min.js?a7fe:1 Uncaught TypeError: Cannot set property 'axios' of undefined
```

VueAxios version: 3.0.1
Axios version: 0.20.0

**Comment by imcvampire** [comment]
Please remember that `vue-axios` 3 only supports vuejs 3. The latest version (with backward compatibility) hasn't been published yet

**Comment by KokoulinM** [comment]
Do I need to do it?

**Comment by avi12** [comment]
> Please remember that `vue-axios` 3 only supports vuejs 3. The latest version (with backward compatibility) hasn't been published yet

That explains it.
So I basically need to install the latest `vue-axios` 2 to fix this problem?

**Comment by imcvampire** [comment]
@KokoulinM. You're welcome. I'm trying it but no luck yet. You can check the `rollup` branch.

**Comment by imcvampire** [comment]
@avi12 Yes!

**Comment by TitanFighter** [comment]
> Please remember that `vue-axios` 3 only supports vuejs 3. The latest version (with backward compatibility) hasn't been published yet

The [matrix](https://github.com/imcvampire/vue-axios#support-matrix) is incorrect - it shows that vue-axios 3 supports Vue v1, v2 and v3.

**Comment by imcvampire** [comment]
> > Please remember that `vue-axios` 3 only supports vuejs 3. The latest version (with backward compatibility) hasn't been published yet
> 
> The [matrix](https://github.com/imcvampire/vue-axios#support-matrix) is incorrect - it shows that vue-axios 3 supports Vue v1, v2 and v3.

No, it's correct. But the backward compatibility code hasn't published yet

**Comment by MarlonDML** [comment]
The latest version(3.1.1) is available

**Comment by imcvampire** [comment]
@MarlonDML Yes!

@TitanFighter @avi12 @KokoulinM Can you update to the latest package and try again?

**Comment by TitanFighter** [comment]
@imcvampire it works. Thanks.

**Comment by avi12** [comment]
@imcvampire Seems to be working now
