### ISSUE TITLE
How can I configure headers to send CSRF token?

### ISSUE THREAD

**Issue by ankitrg** [imcvampire/vue-axios#6]
I am trying to make a post call but due to token csrf protection, the calls fail. I can send csrf token with each call, but I want to configure it at global level.

**Comment by imcvampire** [comment]
You can try: 
```
import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'

Vue.use(VueAxios, axios)

Vue.axios.defaults.headers.common['Authorization'] = AUTH_TOKEN
```

**Comment by hojit** [comment]
Vue.axios.defaults.headers.common['Authorization'] = AUTH_TOKEN
这个设置好像是无效的。
