### ISSUE TITLE
IsURLSameOrigin error when testing the api locally

### ISSUE THREAD

**Issue by WinnersProx** [imcvampire/vue-axios#60]
As stated on the documentation page, i always configure my `main.js` file this way

```
import axios from 'axios';
import VueAxios from 'vue-axios';
Vue.use(VueAxios, axios);
```
However, when trying to hit a local api endpoint (like localhost:8000) it throws the following error and never proceeds the request

`
Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined
    at isURLSameOrigin
`

It can't be a problem with CORS because when I try to use `axios.get` or the browser `fetch` API it works fine

**Comment by imcvampire** [comment]
I can check https://github.com/axios/axios/issues/632? Is it the same problem?

**Comment by WinnersProx** [comment]
It looks to be the same but looking at [the referenced issue](https://github.com/axios/axios/issues/632), people are kinda giving unproven solutions and still don't provide the cause of this issue. it may also be easier to fix for some people when the cause is provided

**Comment by imcvampire** [comment]
@WinnersProx Agree! So, can you provide a simple reproduction?

**Comment by WinnersProx** [comment]
Sorry on this issue, it was actually my bad even if it seems to be a bad user interface

I checked my `.env` and found that my base url was missing a forward slash which URL,  funny enough it couldn't send any request and i didn't know what was going on.

Once again sorry, this issue can be closed @imcvampire
