### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by makurtu** [imcvampire/vue-axios#67]
Hi!

I have an issue implementing VueAxios on Vue 3 project.

I'm installing this way:

```js
// main.js
import { createApp } from 'vue'
import App from './App.vue'
import axios from 'axios'
import VueAxios from 'vue-axios'

createApp(App)
    .use(VueAxios, axios)
    .mount('#app')
```

And then, in my component:

```js
// /components/test.js

<template>
    <button class="btn btn-primary" @click="getUser">Get user</button>
</template>

<script>

export default {
    setup() {

        function getUser() {
            this.axios.get("/api/me").then(({ data }) => {
                console.log(data);
            });
        }

        return {
            getUser,
        };
    },
};
</script>
```

But it throws the error `Cannot read property 'get' of undefined` when click on button. So maybe there is an error when installing `axios` globally.

Versions:

```
"axios": "^0.20.0",
"vue": "^3.0.0",
"vue-axios": "^3.1.1"
```

**Comment by xiaoyao316** [comment]
@makurtu  Do not use `this` in the setup option.

**Comment by makurtu** [comment]
Ouch! Sorry, this is not my working code, I writed it as example and made a mistake.

Finally I made it works, but I had to read this solution: https://stackoverflow.com/questions/64040286/access-this-root-in-vue-js-3-setup

There is a codesandbox working as expected: https://codesandbox.io/s/icy-river-t7sg0

**Now I have a question:**

Do you know a better aproach? I don't like (re)importing the whole app again to use the global axios object. I need to do this way because I need to put global authentication on axios requests :pensive:

**Comment by luffynando** [comment]
Another option maybe is using getCurrentInstance.
In vue docs: https://v3.vuejs.org/api/composition-api.html#getcurrentinstance

```javascript
<template>
    <button class="btn btn-primary" @click="getUser">Get user</button>
</template>

<script>
import { getCurrentInstance } from "vue";

export default {
    setup() {
        const internalInstance = getCurrentInstance();
        function getUser() {
            const axiosInstance = internalInstance.appContext.app.axios; // or $http
            axiosInstance.get("/api/me").then(({ data }) => {
                console.log(data);
            });
        }

        return {
            getUser,
        };
    },
};
</script>
```

**Comment by makurtu** [comment]
Well, maybe this issue can be closed.

I finally used an `export` on whole `axios` lib. This implementation gives me a full control on `axios` lib on all components, so I can set an `Auth bearer token` on login component and can read `auth state` on all components. I can also set a `apiBaseUrl` on `axios instance` and all calls from any component will start by this configuration.

In conclusion, I no longer use this `vue-axios` lib so I get same aproach with native axios plus exporting library and use it in components when I need it. Btw, thanks @luffynando by contributing, I didn't know this function, thanks!
