### ISSUE TITLE
Can't set global headers.

### ISSUE THREAD

**Issue by Pitu** [imcvampire/vue-axios#7]
To use a global header on each Axios request one would normally use something like this:
```js
axios.defaults.headers.common.Authorization = token;
axios.defaults.headers.common['Authorization'] = token;
```
But this is not working with Vue, at least for me. Trying to set the global token by using either `this.axios` or `Vue.axios` gives the same result which is the header not being sent at all. Related to #1 as well.

Any ideas?

**Comment by imcvampire** [comment]
This is what I use in my production code and it works like charm
```
const setAuthorizationHeader = (token) => {
  Vue.axios.defaults.headers.common.Authorization = token ? `Bearer ${token}` : ''
}
```

**Comment by Pitu** [comment]
Where are you setting this if I may ask?

**Comment by imcvampire** [comment]
In my store (using vuex). Because I have to set token when user logins.

**Comment by Pitu** [comment]
Thanks for this, it helped a lot!
