### ISSUE TITLE
 Module ../vue/types has no exported member 'App'

### ISSUE THREAD

**Issue by altapo** [imcvampire/vue-axios#71]
![phpstorm64_BAJ1uCtcX7](https://user-images.githubusercontent.com/837355/97144374-23e1f700-1786-11eb-9158-cee2dacf4102.png)

vue 2.6.12
vue-axios 3.1.3

**Comment by vincentharrius** [comment]
I had the exact same problem and realized that the latest version of vue-axios doesnt have support for vue 2.*. I uninstalled the latest version and installed `vue-axios@2.1.4`. Hope this solves your problem aswell

**Comment by altapo** [comment]
> 
> 
> I had the exact same problem and realized that the latest version of vue-axios doesnt have support for vue 2.*. I uninstalled the latest version and installed `vue-axios@2.1.4`. Hope this solves your problem aswell

I did this earlier, just declared support for version 2.*

**Comment by altapo** [comment]
I did this earlier, just declared support for version 2

**Comment by qqilihq** [comment]
Thanks, same issue here. Downgrading worked.

Probably I’m misreading the compatibility matrix? 🤔 

![image](https://user-images.githubusercontent.com/2172260/99788662-b07f9b00-2b21-11eb-9099-7988f914017a.png)

**Comment by imcvampire** [comment]
Ops .... The type definition file only works for vuejs 3. Can anyone know how to make it supports both 2 and 3?

**Comment by xiaofan9** [comment]
> Ops .... The type definition file only works for vuejs 3. Can anyone know how to make it supports both 2 and 3?

Try to create an .eslintignore file with the following content:
![image](https://user-images.githubusercontent.com/16103130/100566520-3d380f00-3301-11eb-814b-5444bd0f4fa3.png)

**Comment by imcvampire** [comment]
> > Ops .... The type definition file only works for vuejs 3. Can anyone know how to make it supports both 2 and 3?
> 
> Try to create an .eslintignore file with the following content:
> ![image](https://user-images.githubusercontent.com/16103130/100566520-3d380f00-3301-11eb-814b-5444bd0f4fa3.png)

But it will make the definition file doesn't work for vuejs 3, won't it?

**Comment by xiaofan9** [comment]
> > > Ops .... The type definition file only works for vuejs 3. Can anyone know how to make it supports both 2 and 3?
> > 
> > 
> > Try to create an .eslintignore file with the following content:
> > ![image](https://user-images.githubusercontent.com/16103130/100566520-3d380f00-3301-11eb-814b-5444bd0f4fa3.png)
> 
> But it will make the definition file doesn't work for vuejs 3, won't it?

I am going to try
