### ISSUE TITLE
NPM audit reports vulnerabilities associated with rollup-babel dependency

### ISSUE THREAD

**Issue by jpicton** [imcvampire/vue-axios#72]
Running an NPM audit against vue-axios 3.1.2 gives the following report:

```
[high] Regular Expression Denial of Service
 - dependencies: vue-axios>rollup-babel>babel-core>minimatch
--------------------------------------------------
[high] Prototype Pollution
 - dependencies: vue-axios>rollup-babel>babel-core>babel-plugin-proto-to-assign>lodash
 - dependencies: vue-axios>rollup-babel>babel-core>lodash
```

I think there's a couple of issues here:

1. rollup-babel has been superseded by rollup-plugin-babel, so you should only required the latter (you currently have dependencies on both)
2. Both rollup-babel and rollup-plugin-babel have been placed under `dependencies`, when I believe they should be `devDependencies`

vue-axios 3.1.3 (your latest release at the time of writing) also has this problem, so upgrading isn't a solution. I believe that you'll need to drop rollup-babel and move rollup-plugin-babel to `devDependencies`, and release a patch.

**Comment by imcvampire** [comment]
Thanks for the report! Will try to update ASAP!
