### ISSUE TITLE
How can I use this in Vuex store with Vue 3

### ISSUE THREAD

**Issue by RitikPatni** [imcvampire/vue-axios#74]
In Vue 2 I was writing all my API calls in Vuex actions using 
```
Vue.axios.get
Vue.axios.post
```
But now when I try to use the same I get this error
```
can't access property "axios"
```
I've imported this as suggested in the docs
```
const app = createApp(App).use(store).use(router).use(VueAxios, axios)
  .mount('#app');
export default app;
```

**Comment by imcvampire** [comment]
I expect this pkg works like your code. Can you provide a simple reproduction?

**Comment by RitikPatni** [comment]
@imcvampire Please check 
https://codesandbox.io/s/charming-banach-3oxy9?file=/src/store/Login/actions.js

**Comment by luffynando** [comment]
@RitikPatni in vue 3 use getCurrentInstance

In your code actions.js
```javascript
import { getCurrentInstance } from "vue";";

const actions = {
  getBasicInfo(context) {
    return new Promise((resolve, reject) => {
      getCurrentInstance()
        .appContext.app.$http //or axios 
        .get("https://networkcalc.com/api/ip/10.0.1.15/27?binary=1", {})
        .then((response) => {
          resolve(response.data);
        })
        .catch((err) => {
          reject(err);
        });
    });
  }
};
export default actions;
```

**Comment by RitikPatni** [comment]
@luffynando Now I'm getting 
```
can't access property "get", _vue.getCurrentInstance.axios is undefined
```
I've also modified the reproduction [here](https://codesandbox.io/s/vuex-axios-demo-3oxy9?file=/src/store/Login/actions.js) . Can you please check

**Comment by RitikPatni** [comment]
Thanks @luffynando

**Comment by RitikPatni** [comment]
@luffynando As per your suggestions I was using getCurrentInstance to use axios in actions. but the problem with that is it can only be used onMount of application so if I want to call an action for form submission or something else I won't be able to do that with getCurrentInstance. 

I checked the documentation and all I could found was [this](https://v3.vuejs.org/api/composition-api.html#getcurrentinstance)
![image](https://user-images.githubusercontent.com/16117262/99521793-db9baa80-29ba-11eb-9879-9f576de5718e.png)
but this is of no use as actions don't have any Lifecycle hooks and it would not be right to call an action just to save the instance onMount.

@imcvampire @luffynando if any of you have any solution please help. I'll be using it axios from the component in the meantime.

Thanks

**Comment by luffynando** [comment]
@RitikPatni can you upload code example? 
In the store it should work fine because it works when the root instance has already been mounted

**Comment by RitikPatni** [comment]
@luffynando https://codesandbox.io/s/vuex-axios-demo-3oxy9?file=/src/App.vue
I've added a button that dispatches the action where the API was added. The same code works when it is used on mounted. You can uncomment the code in mounted in case you want to test that.

**Comment by luffynando** [comment]
it works fine if you use composition api as explained, but in the code you send you use options api, then it doesn't work like that anymore. But with current options api, you can inyect in root file.
In main.js
```javascript
import { createApp } from "vue";
import axios from "axios";
import VueAxios from "vue-axios";
import App from "./App.vue";
import store from "./store";

const app = createApp(App).use(store).use(VueAxios, axios).mount("#app");
store.$http = app.$http;
store.axios = app.axios;
export default app;
```
in actions.js
```javascript
const actions = {
  getBasicInfo(context) {
    return new Promise((resolve, reject) => {
      this.$http // or this.axios
        .get("https://networkcalc.com/api/ip/10.0.1.15/27?binary=1", {})
        .then((response) => {
          console.log(response.data);
          resolve(response.data);
        })
        .catch((err) => {
          reject(err);
        });
    });
  }
};
export default actions;
```

**Comment by RitikPatni** [comment]
Thanks @luffynando for the help.

**Comment by imcvampire** [comment]
I'm thinking about adding 
```
store.$http = app.$http;
store.axios = app.axios;
``` 

to `vue-axios`

**Comment by KiwiChris-xx** [comment]
when trying to use with @luffynando example within modules I get undefined
store moduleName TypeError: Cannot read properties of undefined (reading 'axios')

any thoughts on using axios within modules?
