### ISSUE TITLE
Support Vue 3 with VueAxios via CDN

### ISSUE THREAD

**Issue by msg7086** [imcvampire/vue-axios#82]
How to reproduce:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test Page</title>
</head>
<body>
  <div id="app"></div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/3.0.2/vue.global.prod.js" integrity="sha512-M8VjsuCj1iBzrwKloFNjvQBmFXT2oF0MWExoLGpQT2nEx5tq7CP+BhWGJdczT1LoWAhyqHh+LJ6ihHSVGyclHw==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.0/axios.min.js" integrity="sha512-DZqqY3PiOvTP9HkjIWgjO6ouCbq+dxqWoJZ/Q+zPYNHmlnI2dQnbJ5bxAHpAMw+LXRm4D72EIRXzvcHQtE8/VQ==" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-axios@3.2.0/dist/vue-axios.es5.js"></script>
</body>
</html>
```

Error message:

```
vue-axios.es5.js:1 Uncaught TypeError: Vue.use is not a function
    at vue-axios.es5.js:1
    at vue-axios.es5.js:1
```

Vue.use has been removed in Vue 3.

**Comment by djom202** [comment]
Hi, happen the same with npm.

![image](https://user-images.githubusercontent.com/1834808/112885438-60e44980-9096-11eb-8cb1-adc539c6f5e8.png)

**Comment by imcvampire** [comment]
@djom202 seems like it isn't `vue-axios` bug. Could you provide a simple reproduction?

**Comment by djom202** [comment]
Hi @imcvampire, Also I'm trying to use in vue v2 and it's happing the same, I'm just importing the dependencies and trying to use it.

```javascript
// main.js
import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'
Vue.use(VueAxios, axios)
```

```javascript
// helper file
import Vue from 'vue'

exports.urlShorter = async (url, alias) => {
  const request = `https://api.php?key=${process.env.VUE_APP_APIKEY}&short=${encodeURI(url)}&name=${alias}`

  console.log('this.axios', this.axios)
  console.log('this.$http', this.$http)
  console.log('Vue.axios', Vue.axios)

  const resp = await this.$http.get(request).then(response => {
    console.log(response.data)
  })

  console.log('resp', resp)
}
```

![image](https://user-images.githubusercontent.com/1834808/114499283-5fb13180-9beb-11eb-84ca-dece2eaec2eb.png)

**Comment by gregbaker** [comment]
I am having the same problem as @msg7086. The provided HTML causes the given exception. Same with vue-axios 3.2.4 and when the files are linked with a `<script>` directly from a local copy.

**Comment by imcvampire** [comment]
Is this what are you using? https://jsfiddle.net/imcvampire/t8a0yjbp/3/

**Comment by gregbaker** [comment]
Yes, that reproduces the problem I'm having.

**Comment by imcvampire** [comment]
Maybe, Vue doesn't export `Vue` as a global var anymore.

**Comment by gregbaker** [comment]
It does: `Vue.createApp` is still the way to create the application object.

The instructions for using a plugin have changed between [version 2 instructions](https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin) and [version 3 instructions](https://v3.vuejs.org/guide/plugins.html#writing-a-plugin). Instead of `Vue.use(MyPlugin)`, the instruction is `app.use(MyPlugin, optionalArguments)`.

I think the right solution is to check for `window.Vue.use`:
```js
if (typeof exports == "object") {
  module.exports = plugin;
} else if (typeof define == "function" && define.amd) {
  define([], function(){ return plugin });
} else if (window.Vue && window.axios && window.Vue.use) {
  Vue.use(plugin, window.axios);
}
```

**Comment by imcvampire** [comment]
@gregbaker Nice, thank you! If you're okay, feel free to create a merge request.
