### ISSUE TITLE
vue-axios.es5.js.map: error: Expected end of file

### ISSUE THREAD

**Issue by baradhili** [imcvampire/vue-axios#86]
noticed this in 3.2.2
checking the file with a json linter also got the same error so its not just vite :)

found "AAQyE"
    1 │ ...window.axios);\n  }\n})();\n"]}AAQyE,UAC1DF,OAAOE,QAAU4V,EACS,mBAA...
      ╵

**Comment by nbeezander** [comment]
same

**Comment by vesper8** [comment]
Same error, can't use vitejs as a result. Still happening on 3.2.2

This is the last ~hundred characters of `vue-axios.es5.js.map`

```
else if (window.Vue && window.axios) {\n    Vue.use(plugin, window.axios);\n  }\n})();\n"]}AAQyE,UAC1DF,OAAOE,QAAU4V,EACS,mBAAVQ,QAAwBA,OAAOC,IAC/CD,OAAO,GAAI,WACT,OAAOR,IAEAU,OAAOC,KAAOD,OAAOR,OAC9BS,IAAIC,IAAIZ,EAAQU,OAAOR,OApD3B"}
```

@imcvampire could you please look into this?

Many thanks

**Comment by vesper8** [comment]
Following up. I noticed that v3 has dropped support for vue2.. and I'm still using vue 2 and had been using vue-axios v3.. so.. I guess they didn't completely drop support because it was still working.. but in any case I reverted to version 2.1.5 and I no longer have this issue

**Comment by baradhili** [comment]
I found if I slice off those characters everything works fine...

**Comment by imcvampire** [comment]
I haven't found what causes these characters. Any support is welcome!

@vesper8 v3 still supports vue2!

**Comment by imcvampire** [comment]
I have released a new version named 3.2.3. Please kindly update and inform whether the error has gone.

**Comment by baradhili** [comment]
No still there I'm afraid

**Comment by imcvampire** [comment]
I have disabled source map in 3.2.4, so you can use the package now.
