### ISSUE TITLE
直接下下来运行，报20个错误，是我这边环境的问题吗？

### ISSUE THREAD

**Issue by awtmeng** [imcvampire/vue-axios#9]
(unknown) [Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <VNav> at D:\my_fe\xyy-vue-master\xyy-vue-master\src\components\nav.vue)warn
(unknown) [Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <TravelList> at D:\my_fe\xyy-vue-master\xyy-vue-master\src\components\travelList.vue)warn
(unknown) [Vue warn]: Error in render function: 
(found in <VTabar> at D:\my_fe\xyy-vue-master\xyy-vue-master\src\components\tabar.vue)warn
(unknown) TypeError: Cannot read property 'path' of undefined(…)handleError
5(unknown) [Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <VSidebar> at D:\my_fe\xyy-vue-master\xyy-vue-master\src\components\sidebar.vue)warn
(unknown) [Vue warn]: Error in render function: 
(found in <VTabar> at D:\my_fe\xyy-vue-master\xyy-vue-master\src\components\tabar.vue)warn
(unknown) TypeError: Cannot read property 'path' of undefined(…)

**Comment by StevenYuysy** [comment]
It's obvious that is your own problem, check your code plz.
---
很明显这个仓库和你的报错没有关系，检查一下你的代码 
- `nav.vue` `travelList.vue`，这里你没有正确的注册组件，
- `tabar.vue` `sidebar.vue` ，检查一下哪些对象引用了 `path` ，这些对象是不是  `undefined`
